insert into baa (name, manufacturer, description) values ('MESEH-37441', 'Venlafaxine Hydrochloride', 'Dalea emarginata (Torr. & A. Gray) Shinners');
insert into baa (name, manufacturer, description) values ('AYCTF-07004', 'Publix', 'Oxalis nelsonii (Small) R. Knuth');
insert into baa (name, manufacturer, description) values ('RRIME-18842', 'Hydrocortisone anti-itch plus', 'Chenopodium urbicum L.');
insert into baa (name, manufacturer, description) values ('KCFCT-27072', 'Lioresal', 'Carex debilis Michx. var. strictior L.H. Bailey');
insert into baa (name, manufacturer, description) values ('DUKMR-30135', 'MICONAZOLE', 'Hibiscadelphus bombycinus Forbes');
insert into baa (name, manufacturer, description) values ('TMVQD-21067', 'Oxygen', 'Philadelphus oreganus Nutt. ex Torr. & A. Gray');
insert into baa (name, manufacturer, description) values ('TNYGT-16849', 'Antizol', 'Orthilia secunda (L.) House');
insert into baa (name, manufacturer, description) values ('XXURO-51779', 'Escitalopram', 'Vangueria madagascariensis J.F. Gmel.');
insert into baa (name, manufacturer, description) values ('SYAFS-97941', 'Monsels Solution', 'Carissa edulis (Forssk.) Vahl [excluded]');
insert into baa (name, manufacturer, description) values ('SIQNA-27324', 'Desipramine Hydrochloride', 'Diplotomma ambiguum (Ach.) Flagey');
insert into baa (name, manufacturer, description) values ('MDHJA-38426', 'Oxygen', 'Lupinus wyethii S. Watson ssp. wyethii');
insert into baa (name, manufacturer, description) values ('STYJT-19755', 'Atorvastatin Calcium', 'Nesaea longipes A. Gray');
insert into baa (name, manufacturer, description) values ('NJZSZ-32620', 'Delsym Night Time', 'Trichostomopsis brevifolia E.B. Bartram');
insert into baa (name, manufacturer, description) values ('FMWWT-67418', 'Lyrica', 'Eriogonum effusum Nutt.');
insert into baa (name, manufacturer, description) values ('NMXAI-24919', 'Carvedilol', 'Chionanthus domingensis Lam.');
insert into baa (name, manufacturer, description) values ('VTNLW-93908', 'ecologique', 'Oncidium floridanum Ames');
insert into baa (name, manufacturer, description) values ('VYHGW-24697', 'Medroxyprogesterone Acetate', 'Rubus ictus L.H. Bailey');
insert into baa (name, manufacturer, description) values ('BCUQV-49107', 'Tall Ragweed', 'Pittosporum tobira (Thunb.) W.T. Aiton');
insert into baa (name, manufacturer, description) values ('QQXZR-62775', 'EUPHRASIA OFFICINALIS', 'Kumlienia Greene');
insert into baa (name, manufacturer, description) values ('PEIOG-03809', 'TOLNAFTATE ANTIFUNGAL', 'Coccothrinax argentata (Jacq.) L.H. Bailey');
insert into baa (name, manufacturer, description) values ('OQGWE-74212', 'Carvedilol', 'Lapsana communis L.');
insert into baa (name, manufacturer, description) values ('AEPPR-84798', 'Brucella Remedy', 'Poa paucispicula Scribn. & Merr.');
insert into baa (name, manufacturer, description) values ('DPAXK-56643', 'THE SKIN EXTRA BB', 'Lyonia rubiginosa (Pers.) G. Don var. rubiginosa');
insert into baa (name, manufacturer, description) values ('HDYQE-06679', 'ATOPALM BB LIGHT SPF 20 BROAD SPECTRUM SUNSCREEN', 'Dubautia knudsenii Hillebr. ssp. knudsenii');
insert into baa (name, manufacturer, description) values ('MZCIL-26451', 'Terrasil Foot and Nail Anti-Fungal', 'Asclepias emoryi (Greene) Vail');
insert into baa (name, manufacturer, description) values ('YFKIX-04889', 'fexofenadine hydrochloride', 'Paspalum millegrana Schrad.');
insert into baa (name, manufacturer, description) values ('JNQBR-34690', 'EXCEL SPORT', 'Origanum maru L.');
insert into baa (name, manufacturer, description) values ('QMSDC-97400', 'EXTRA STRENGTH STOOL SOFTENER LAXATIVE', 'Phlyctella andensis Nyl.');
insert into baa (name, manufacturer, description) values ('ZZHPG-71438', 'DOXAZOSIN', 'Triosteum aurantiacum E.P. Bicknell var. aurantiacum');
insert into baa (name, manufacturer, description) values ('ISIRW-41826', 'Methylene Blue', 'Crataegus nuda Sarg.');
insert into baa (name, manufacturer, description) values ('LODEH-93999', 'MULTI PERFECTION SUPER', 'Platanthera ×channellii J.P. Folsom');
insert into baa (name, manufacturer, description) values ('TFUMB-33809', 'SINGULAIR', 'Crataegus pringlei Sarg.');
insert into baa (name, manufacturer, description) values ('CLUCA-75091', 'bareMinerals Prime Time BB Primer Daily Defense Broad Spectrum SPF 30', 'Stillingia sylvatica L. ssp. sylvatica');
insert into baa (name, manufacturer, description) values ('KXMMD-92611', 'esika', 'Arceuthobium apachecum Hawksw. & Wiens');
insert into baa (name, manufacturer, description) values ('LTDOX-73658', 'Zohydro', 'Citrullus lanatus (Thunb.) Matsum. & Nakai var. citroides (L.H. Bailey) Mansf.');
insert into baa (name, manufacturer, description) values ('ARNBW-39303', 'CLE DE PEAU BEAUTE SILKY FOUNDATION I', 'Carex buxbaumii Wahlenb.');
insert into baa (name, manufacturer, description) values ('BYBBS-68599', 'Multi-Active Day Early Wrinkle Correcting SPF 15', 'Austrocedrus chilensis (D. Don) Pic. Serm. & Bizzarri');
insert into baa (name, manufacturer, description) values ('FHRAG-79508', 'Maxipime', 'Miconia impetiolaris (Sw.) D. Don ex DC.');
insert into baa (name, manufacturer, description) values ('OPFQZ-00424', 'ibuprofen', 'Cercocarpus montanus Raf.');
insert into baa (name, manufacturer, description) values ('TLNLM-86824', 'flormar PERFECT COVERAGE FOUNDATION SUNSCREEN BROAD SPECTRUM SPF 15 105 Porcelain Ivory', 'Mentzelia nuda (Pursh) Torr. & A. Gray var. nuda');
insert into baa (name, manufacturer, description) values ('GTGVR-63793', 'Misoprostol', 'Chenopodium humile Hook.');
insert into baa (name, manufacturer, description) values ('KTDVJ-83753', 'Coppertone Tanning Dry Oil', 'Justicia comata (L.) Lam.');
insert into baa (name, manufacturer, description) values ('JVBIL-16146', 'Alprazolam', 'Arctostaphylos tomentosa (Pursh) Lindl. ssp. daciticola P.V. Wells');
insert into baa (name, manufacturer, description) values ('OEORT-42444', 'LOSARTAN POTASSIUM AND HYDROCHLOROTHIAZIDE', 'Cleome aculeata L.');
insert into baa (name, manufacturer, description) values ('PIOLF-36980', 'Magnesium Sulfate', 'Scleria ciliata Michx.');
insert into baa (name, manufacturer, description) values ('XOFWY-65028', 'desonide', 'Cotoneaster acuminatus Lindl.');
insert into baa (name, manufacturer, description) values ('ZZWRW-03737', 'SUPER ORIGIN CERAMIDE BB', 'Hymenoclea Torr. & A. Gray ex A. Gray');
insert into baa (name, manufacturer, description) values ('ZVSJH-59592', 'Furosemide', 'Pedicularis bracteosa Benth. var. flavida (Pennell) Cronquist');
insert into baa (name, manufacturer, description) values ('DTVJQ-98907', 'Lithium Carbonate', 'Splachnum luteum Hedw. var. luteum');
insert into baa (name, manufacturer, description) values ('LTWNW-14392', 'Gericare Artificial Tears Lubricant Eye', 'Centaurium venustum (A. Gray) B.L. Rob.');
insert into baa (name, manufacturer, description) values ('JMFUS-51592', 'BENZOCAINE and RESORCINOL', 'Cyanea pilosa A. Gray ssp. pilosa');
insert into baa (name, manufacturer, description) values ('KLPVM-79351', 'Zaliex ALCOHOL-FREE Antiseptic Hand Sanitizer', 'Corydalis pauciflora (Stephan) Pers.');
insert into baa (name, manufacturer, description) values ('HFMIL-59785', 'Levothyroxine Sodium', 'Bryum capillare Hedw. var. capillare');
insert into baa (name, manufacturer, description) values ('JOPEJ-43291', 'Buspirone Hydrochloride', 'Canarium schweinfurthii Engl.');
insert into baa (name, manufacturer, description) values ('DNRWZ-41282', 'Guaiasorb DM', 'Lecania turicensis (Hepp) Müll. Arg.');
insert into baa (name, manufacturer, description) values ('BADOX-86407', 'ZOLPIDEM TARTRATE', 'Atriplex tridentata Kuntze');
insert into baa (name, manufacturer, description) values ('WNBZY-14597', '7 Select Aspirin', 'Festuca viviparoidea Krajina ex Pavlick ssp. viviparoidea');
insert into baa (name, manufacturer, description) values ('OREMQ-09362', 'Labetalol hydrochloride', 'Mimulus palmeri A. Gray');
insert into baa (name, manufacturer, description) values ('KEQVD-19705', 'AVINZA', 'Cyclanthera Schrad.');
insert into baa (name, manufacturer, description) values ('LORXC-44232', 'INDIUM IN 111 CHLORIDE', 'Quercus minima (Sarg.) Small');
insert into baa (name, manufacturer, description) values ('EYFGZ-33615', 'Cefoxitin', 'Centrostegia thurberi A. Gray ex Benth.');
insert into baa (name, manufacturer, description) values ('FZBUH-23027', 'Pediaderm AF', 'Leucothoe fontanesiana (Steud.) Sleumer');
insert into baa (name, manufacturer, description) values ('GZYIY-97540', 'Berberis Vulgaris', 'Trifolium campestre Schreb.');
insert into baa (name, manufacturer, description) values ('COUJQ-13608', 'propylthiouracil', 'Molendoa Lindb.');
insert into baa (name, manufacturer, description) values ('IUYSV-76122', 'Blistex', 'Piper nigrum L.');
insert into baa (name, manufacturer, description) values ('RPULI-68088', 'Risperidone', 'Potamogeton ogdenii Hellquist & Hilton');
insert into baa (name, manufacturer, description) values ('QRLOW-54114', 'Diphenoxylate Hydrochloride and Atropine Sulfate', 'Xanthoparmelia mougeotii (Schaerer) Hale');
insert into baa (name, manufacturer, description) values ('XQNCZ-11413', 'Cedar X Pet Formula', 'Kirschsteiniothelia acerina (Rossman & Wilcox) D. Hawksw.');
insert into baa (name, manufacturer, description) values ('JWALP-31794', 'LANEIGE SKIN VEIL', 'Racomitrium pacificum Irel. & Spence');
insert into baa (name, manufacturer, description) values ('FXYCJ-21526', 'Sunmark enema', 'Cynosurus echinatus L.');
insert into baa (name, manufacturer, description) values ('GRJKL-36529', 'quetiapine fumarate', 'Agrostis clivicola Crampton var. punta-reyesensis Crampton');
insert into baa (name, manufacturer, description) values ('JDYOS-41332', 'Bisacodyl', 'Lobelia niihauensis H. St. John');
insert into baa (name, manufacturer, description) values ('PLHKG-77436', 'Quack Grass', 'Cheirodendron trigynum (Gaudich.) A. Heller ssp. trigynum');
insert into baa (name, manufacturer, description) values ('SOMEV-97015', 'Ibuprofen', 'Allium burlewii Davidson');
insert into baa (name, manufacturer, description) values ('YDNHF-30067', 'Hydromorphone Hydrochloride', 'Packera eurycephala (Torr. & A. Gray) W.A. Weber & Á. Löve var. eurycephala');
insert into baa (name, manufacturer, description) values ('ZZXUU-09429', 'Ondansetron', 'Packera hartiana (A. Heller) W.A. Weber & Á. Löve');
insert into baa (name, manufacturer, description) values ('WGDPQ-86794', 'EZ2go Zero', 'Carex louisianica L.H. Bailey');
insert into baa (name, manufacturer, description) values ('QHDFQ-45394', 'BACITRACIN', 'Gunnera kauaiensis Rock');
insert into baa (name, manufacturer, description) values ('LVIEL-45874', 'Smelt', 'Hibiscadelphus giffardianus Rock');
insert into baa (name, manufacturer, description) values ('CDNYH-19869', 'AntiBac Foam Wash/Aerogreen', 'Matthiola incana (L.) W.T. Aiton');
insert into baa (name, manufacturer, description) values ('VTZUB-68847', 'Losartan Potassium', 'Berkheya Ehrh.');
insert into baa (name, manufacturer, description) values ('FVFIX-38151', 'Plexion', 'Ichnanthus P. Beauv.');
insert into baa (name, manufacturer, description) values ('IEIGM-63637', 'METHAZOLAMIDE', 'Cryptantha oxygona (A. Gray) Greene');
insert into baa (name, manufacturer, description) values ('ZUOEL-62541', 'Old Spice Fresh', 'Hymenophyllum decurrens (Jacq.) Sw.');
insert into baa (name, manufacturer, description) values ('WDUCA-37698', 'Right Guard Sport', 'Zephyranthes proctorii Acev.-Rodr. & M.T. Strong');
insert into baa (name, manufacturer, description) values ('LBGBO-07351', 'Acremonium strictum', 'Calochortus tolmiei Hook. & Arn.');
insert into baa (name, manufacturer, description) values ('YJFTA-45129', 'Panic Ease', 'Symphyotrichum tradescantii (L.) G.L. Nesom');
insert into baa (name, manufacturer, description) values ('MDWEF-67935', 'Levothyroxine Sodium', 'Dalea carthagenensis (Jacq.) J.F. Macbr. var. portoricana Barneby');
insert into baa (name, manufacturer, description) values ('HCVPX-31499', 'Propranolol Hydrochloride', 'Rubus inferior L.H. Bailey');
insert into baa (name, manufacturer, description) values ('LVHTD-52359', 'Leukine', 'Beta procumbens C. Sm.');
insert into baa (name, manufacturer, description) values ('FSNYI-48488', 'Mustard Pollen', 'Paspalum wrightii Hitchc. & Chase');
insert into baa (name, manufacturer, description) values ('IRECK-17361', 'Oxaliplatin', 'Bouteloua uniflora Vasey');
insert into baa (name, manufacturer, description) values ('KDTGN-53451', 'Diovan HCT', 'Hulsea vestita A. Gray ssp. parryi (A. Gray) Wilken');
insert into baa (name, manufacturer, description) values ('ZQTDL-35009', 'CAREONE', 'Symplocos Jacq.');
insert into baa (name, manufacturer, description) values ('DGLDY-70265', 'Cheratussin AC', 'Calycoseris A. Gray');
insert into baa (name, manufacturer, description) values ('SHXVZ-18463', 'Antibacterial Foaming Hand Cleanser', 'Setariopsis auriculata (Fourn.) Scribn.');
insert into baa (name, manufacturer, description) values ('NDLWZ-97362', 'OXACILLIN', 'Gliricidia sepium (Jacq.) Kunth ex Walp.');
insert into baa (name, manufacturer, description) values ('ELKJX-35792', 'Promethazine Hydrochloride', 'Eragrostis unioloides (Retz.) Nees ex Steud.');
insert into baa (name, manufacturer, description) values ('WUTWK-39166', 'Amoxicillin', 'Astragalus diversifolius A. Gray');
insert into baa (name, manufacturer, description) values ('IDFVR-08116', 'Pollens - Trees, Birch Mix', 'Lonicera sempervirens L.');
insert into baa (name, manufacturer, description) values ('VIJYK-15929', 'SKIN CAVIAR CONCEALER FOUNDATION SUNSCREEN SPF 15 - Creme Blush', 'Porotrichum bigelovii (Sull.) Kindb.');
insert into baa (name, manufacturer, description) values ('ENWUS-44405', 'ropinirole', 'Eriogonum microthecum Nutt.');
insert into baa (name, manufacturer, description) values ('BGMHD-34933', 'Bactimicina Allergy', 'Carex krausei Boeckeler');
insert into baa (name, manufacturer, description) values ('DHAYZ-68810', 'Halls', 'Parmelina quercina (Willd.) Hale');
insert into baa (name, manufacturer, description) values ('QRGLJ-28634', 'Allergies Rocky MTNS. U.S.', 'Ceanothus fendleri A. Gray');
insert into baa (name, manufacturer, description) values ('EXJKF-66984', 'Oralair', 'Scopelophila cataractae (Mitt.) Broth.');
insert into baa (name, manufacturer, description) values ('MAZJT-48560', 'Fields of Flowers', 'Sabatia brachiata Elliott');
insert into baa (name, manufacturer, description) values ('DCTKZ-19385', 'DOXEPIN HYDROCHLORIDE', 'Eugeissona utilis Becc.');
insert into baa (name, manufacturer, description) values ('DTHCN-32281', 'Omeprazole', 'Eriochrysis cayennensis P. Beauv.');
insert into baa (name, manufacturer, description) values ('FNFJI-51882', 'Diltiazem Hydrochloride', 'Epiphyllum ackermanii Haw.');
insert into baa (name, manufacturer, description) values ('QBGKG-55368', 'up and up pain relief', 'Tetramolopium consanguineum (A. Gray) Hillebr. ssp. leptophyllum (Sherff) Lowrey');
insert into baa (name, manufacturer, description) values ('DOGZM-05725', 'Golden Pear Antibacterial Foaming Hand Wash', 'Saxifraga nelsoniana D. Don ssp. nelsoniana');
insert into baa (name, manufacturer, description) values ('CCZLP-72416', 'Clarithromycin', 'Nemacladus glanduliferus Jeps.');
insert into baa (name, manufacturer, description) values ('XDNOQ-81351', '04 Moisture Foundation SPF 15', 'Camissonia claviformis (Torr. & Frém.) P.H. Raven ssp. claviformis');
insert into baa (name, manufacturer, description) values ('BGGZI-16185', 'RAGWITEK', 'Camissonia claviformis (Torr. & Frém.) P.H. Raven ssp. yumae (P.H. Raven) P.H. Raven');
insert into baa (name, manufacturer, description) values ('KEFAE-89208', 'Tamsulosin Hydrochloride', 'Aliciella stenothyrsa (A. Gray) J.M. Porter');
insert into baa (name, manufacturer, description) values ('TFZUI-97558', 'Povidone-Iodine Prep Pad', 'Vicia unijuga A. Braun');
insert into baa (name, manufacturer, description) values ('WKMOD-48248', 'Baclofen', 'Mallotus Lour.');
insert into baa (name, manufacturer, description) values ('DKSNS-47031', 'Hydrocortisone', 'Orthothecium diminutivum (Grout) H.A. Crum, Steere & L.E. Anderson');
insert into baa (name, manufacturer, description) values ('OSGSC-12516', 'Propranolol Hydrochloride', 'Canbya Parry ex A. Gray');
insert into baa (name, manufacturer, description) values ('WELDA-21829', 'CLE DE PEAU BEAUTE SILKY FOUNDATION I', 'Croton glandulosus L. var. lindheimeri Müll. Arg.');
insert into baa (name, manufacturer, description) values ('VHZAS-19881', 'CHILDRENS ALLERGY', 'Dalea scandens (Mill.) R.T. Clausen var. paucifolia (J.M. Coult.) Barneby');
insert into baa (name, manufacturer, description) values ('WAMAM-37358', 'Eye Drops AC', 'Acer glabrum Torr.');
insert into baa (name, manufacturer, description) values ('SJCYU-22581', 'Genuine Hand Sanitizer', 'Lupinus sericeus Pursh ssp. sericeus');
insert into baa (name, manufacturer, description) values ('MFNZU-84349', 'Quetiapine fumarate', 'Desmodium canescens (L.) DC.');
insert into baa (name, manufacturer, description) values ('CLHQA-75326', 'DIGOXIN', 'Vitex glabrata R. Br.');
insert into baa (name, manufacturer, description) values ('FBKQL-51297', 'Aminophylline', 'Phacelia leptosepala Rydb.');
insert into baa (name, manufacturer, description) values ('CWZTV-81639', 'Hot Spot', 'Carex louisianica L.H. Bailey');
insert into baa (name, manufacturer, description) values ('TJBJK-92570', 'Fentanyl', 'Agalinis heterophylla (Nutt.) Small ex Britton');
insert into baa (name, manufacturer, description) values ('VKSGF-16260', 'White Mulberry', 'Phleum paniculatum Huds.');
insert into baa (name, manufacturer, description) values ('WIDXF-73010', 'Tegretol', 'Pisonia taina Trejo');
insert into baa (name, manufacturer, description) values ('GLEFV-28304', 'ondansetron hydrochloride', 'Cenchrus palmeri Vasey');
insert into baa (name, manufacturer, description) values ('EDCPO-76421', 'Gabapentin', 'Ferula gummosa Boiss.');
insert into baa (name, manufacturer, description) values ('FONJL-58080', 'Milk of Magnesia', 'Cyanea linearifolia Rock');
insert into baa (name, manufacturer, description) values ('BIJZY-37993', 'Waterless Anti-Bacterial Hand Cleanser', 'Heuchera brevistaminea Wiggins');
insert into baa (name, manufacturer, description) values ('JXDRM-49638', 'Peptic Relief', 'Poa sieberiana Spreng.');
insert into baa (name, manufacturer, description) values ('IPZMQ-10226', 'mapap', 'Physcomitrium washingtoniense H.A. Crum & L.E. Anderson');
insert into baa (name, manufacturer, description) values ('BKIHZ-31506', 'Oxygen', 'Epilobium canum (Greene) P.H. Raven ssp. canum');
insert into baa (name, manufacturer, description) values ('JSQSE-50743', 'Anticavity Fluoride Rinse', 'Carex lacustris Willd.');
insert into baa (name, manufacturer, description) values ('VDJTB-85590', 'Escitalopram Oxalate', 'Hechtia texensis S. Watson');
insert into baa (name, manufacturer, description) values ('ZPBWL-08594', 'Calamine Plus', 'Callitriche fassettii Schotsman');
insert into baa (name, manufacturer, description) values ('ZBLMU-55564', 'Green Olive', 'Lupinus sierrae-blancae Wooton & Standl.');
insert into baa (name, manufacturer, description) values ('DKWBB-14570', 'CEFTRIAXONE', 'Campylopus oerstedianus (Müll. Hal.) Mitt.');
insert into baa (name, manufacturer, description) values ('ZBPDK-82174', 'AGARICINUM', 'Ipomoea ternifolia Cav. var. leptotoma (Torr.) J.A. McDonald');
insert into baa (name, manufacturer, description) values ('ZUBIO-24512', 'natural laxative', 'Piptatheropsis Romasch., P.M. Peterson & R. J. Soreng');
insert into baa (name, manufacturer, description) values ('UQNQY-81897', 'Rohto', 'Phacelia linearis (Pursh) Holz.');
insert into baa (name, manufacturer, description) values ('KTOSE-23749', 'Diphenhydramine Hydrochloride', 'Arctostaphylos parryana Lemmon ssp. tumescens J.E. Keeley, L. Boykin & A. Massihi');
insert into baa (name, manufacturer, description) values ('TXXVD-72914', 'Hemorrhoidal Relief', 'Cuscuta cephalanthi Engelm.');
insert into baa (name, manufacturer, description) values ('ZIXQC-75135', 'PROBLEND Antibacterial Liquid Cleanser', 'Corema conradii (Torr.) Torr. ex Loudon');
insert into baa (name, manufacturer, description) values ('CMNJM-38478', 'Cyclobenzaprine Hydrochloride', 'Nidema Britton & Millsp.');
