insert into preparation (complex_name, description) values ('Nondisp oblique fx shaft of l ulna, 7thF', 'Nondisplaced oblique fracture of shaft of left ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into preparation (complex_name, description) values ('Other non-in-line roller-skating accident, sequela', 'Other non-in-line roller-skating accident, sequela');
insert into preparation (complex_name, description) values ('Unspecified disorder of vitreous body', 'Unspecified disorder of vitreous body');
insert into preparation (complex_name, description) values ('Corros third degree of head, face, and neck, unsp site, sqla', 'Corrosion of third degree of head, face, and neck, unspecified site, sequela');
insert into preparation (complex_name, description) values ('Other malformation of placenta', 'Other malformation of placenta');
insert into preparation (complex_name, description) values ('Disp fx of third metatarsal bone, unsp foot, init', 'Displaced fracture of third metatarsal bone, unspecified foot, initial encounter for closed fracture');
insert into preparation (complex_name, description) values ('Displ osteochon fx unsp patella, subs for clos fx w malunion', 'Displaced osteochondral fracture of unspecified patella, subsequent encounter for closed fracture with malunion');
insert into preparation (complex_name, description) values ('Complications of internal orthopedic prosth dev/grft', 'Complications of internal orthopedic prosthetic devices, implants and grafts');
insert into preparation (complex_name, description) values ('Other skateboard accident, initial encounter', 'Other skateboard accident, initial encounter');
insert into preparation (complex_name, description) values ('Sltr-haris Type III physl fx upper end humer, left arm, init', 'Salter-Harris Type III physeal fracture of upper end of humerus, left arm, initial encounter for closed fracture');
insert into preparation (complex_name, description) values ('Complete traumatic amputation at r shoulder jt, sequela', 'Complete traumatic amputation at right shoulder joint, sequela');
insert into preparation (complex_name, description) values ('Mech compl of implnt elec nstim, generator, init', 'Other mechanical complication of implanted electronic neurostimulator, generator, initial encounter');
insert into preparation (complex_name, description) values ('Disorder of ligament, right elbow', 'Disorder of ligament, right elbow');
insert into preparation (complex_name, description) values ('Open bite of abdominal wall, epigst rgn w penet perit cav', 'Open bite of abdominal wall, epigastric region with penetration into peritoneal cavity');
insert into preparation (complex_name, description) values ('Strain flexor musc/fasc/tend of unsp fngr at forarm lv, init', 'Strain of flexor muscle, fascia and tendon of finger of unspecified finger at forearm level, initial encounter');
insert into preparation (complex_name, description) values ('Nondisp Maisonneuve''s fx l leg, 7thG', 'Nondisplaced Maisonneuve''s fracture of left leg, subsequent encounter for closed fracture with delayed healing');
insert into preparation (complex_name, description) values ('Toxic effect of chewing tobacco, intentional self-harm, init', 'Toxic effect of chewing tobacco, intentional self-harm, initial encounter');
insert into preparation (complex_name, description) values ('Cochlear otosclerosis, bilateral', 'Cochlear otosclerosis, bilateral');
insert into preparation (complex_name, description) values ('Choroidal degeneration, unspecified, bilateral', 'Choroidal degeneration, unspecified, bilateral');
insert into preparation (complex_name, description) values ('Nondisp fx of proximal phalanx of unspecified finger', 'Nondisplaced fracture of proximal phalanx of unspecified finger');
insert into preparation (complex_name, description) values ('Puncture wound w/o foreign body of right upper arm, sequela', 'Puncture wound without foreign body of right upper arm, sequela');
insert into preparation (complex_name, description) values ('Lead-induced gout, right ankle and foot', 'Lead-induced gout, right ankle and foot');
insert into preparation (complex_name, description) values ('Hypertensive retinopathy, unspecified eye', 'Hypertensive retinopathy, unspecified eye');
insert into preparation (complex_name, description) values ('Poisn by centr-acting/adren-neurn-block agnt, slf-hrm, subs', 'Poisoning by centrally-acting and adrenergic-neuron-blocking agents, intentional self-harm, subsequent encounter');
insert into preparation (complex_name, description) values ('Dislocation of internal left hip prosthesis, subs encntr', 'Dislocation of internal left hip prosthesis, subsequent encounter');
insert into preparation (complex_name, description) values ('Burn of second degree of back of left hand, sequela', 'Burn of second degree of back of left hand, sequela');
insert into preparation (complex_name, description) values ('Fracture of alveolus of right mandible, 7thK', 'Fracture of alveolus of right mandible, subsequent encounter for fracture with nonunion');
insert into preparation (complex_name, description) values ('Injury of lateral plantar nerve, unsp leg, init encntr', 'Injury of lateral plantar nerve, unspecified leg, initial encounter');
insert into preparation (complex_name, description) values ('Osteitis deformans in neoplastic diseases, unspecified site', 'Osteitis deformans in neoplastic diseases, unspecified site');
insert into preparation (complex_name, description) values ('Abscess of tendon sheath, right thigh', 'Abscess of tendon sheath, right thigh');
insert into preparation (complex_name, description) values ('Corrosion of unsp degree of back of left hand, init encntr', 'Corrosion of unspecified degree of back of left hand, initial encounter');
insert into preparation (complex_name, description) values ('Long term (current) use of antocoag/antithrom/angiplate', 'Long term (current) use of anticoagulants and antithrombotics/antiplatelets');
insert into preparation (complex_name, description) values ('Corrosion of third degree of forehead and cheek', 'Corrosion of third degree of forehead and cheek');
insert into preparation (complex_name, description) values ('Unsp physl fx low end humer, l arm, subs for fx w delay heal', 'Unspecified physeal fracture of lower end of humerus, left arm, subsequent encounter for fracture with delayed healing');
insert into preparation (complex_name, description) values ('Pressure ulcer of left hip, stage 1', 'Pressure ulcer of left hip, stage 1');
insert into preparation (complex_name, description) values ('Bent bone of r ulna, subs for opn fx type 3A/B/C w malunion', 'Bent bone of right ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion');
insert into preparation (complex_name, description) values ('Corrosion of first degree of left toe(s) (nail)', 'Corrosion of first degree of left toe(s) (nail)');
insert into preparation (complex_name, description) values ('Allergic purpura', 'Allergic purpura');
insert into preparation (complex_name, description) values ('Oth injury of greater saphenous vein at lower leg level', 'Other specified injury of greater saphenous vein at lower leg level');
insert into preparation (complex_name, description) values ('Complete loss of teeth, unspecified cause, class IV', 'Complete loss of teeth, unspecified cause, class IV');
insert into preparation (complex_name, description) values ('Menstrual migraine, intractable, without status migrainosus', 'Menstrual migraine, intractable, without status migrainosus');
insert into preparation (complex_name, description) values ('Unsp fx lower end of l ulna, subs for clos fx w delay heal', 'Unspecified fracture of lower end of left ulna, subsequent encounter for closed fracture with delayed healing');
insert into preparation (complex_name, description) values ('Pnctr w foreign body of unsp external genital organs', 'Puncture wound with foreign body of unspecified external genital organs');
insert into preparation (complex_name, description) values ('Unsp inj flexor musc/fasc/tend r rng fngr at wrs/hnd lv', 'Unspecified injury of flexor muscle, fascia and tendon of right ring finger at wrist and hand level');
insert into preparation (complex_name, description) values ('Body mass index (BMI) 30-39, adult', 'Body mass index (BMI) 30-39, adult');
insert into preparation (complex_name, description) values ('Disp fx of unsp ulna styloid pro, 7thD', 'Displaced fracture of unspecified ulna styloid process, subsequent encounter for closed fracture with routine healing');
insert into preparation (complex_name, description) values ('Unsp fx shaft of right tibia, subs for clos fx w malunion', 'Unspecified fracture of shaft of right tibia, subsequent encounter for closed fracture with malunion');
insert into preparation (complex_name, description) values ('Partial traumatic amputation of two or more left lesser toes', 'Partial traumatic amputation of two or more left lesser toes');
insert into preparation (complex_name, description) values ('Other dislocation of left wrist and hand, initial encounter', 'Other dislocation of left wrist and hand, initial encounter');
insert into preparation (complex_name, description) values ('Unspecified fracture of shaft of right tibia, sequela', 'Unspecified fracture of shaft of right tibia, sequela');
insert into preparation (complex_name, description) values ('Unsp fx low end l tibia, 7thE', 'Unspecified fracture of lower end of left tibia, subsequent encounter for open fracture type I or II with routine healing');
insert into preparation (complex_name, description) values ('Broken internal left hip prosthesis', 'Broken internal left hip prosthesis');
insert into preparation (complex_name, description) values ('Unspecified fracture of upper end of ulna', 'Unspecified fracture of upper end of ulna');
insert into preparation (complex_name, description) values ('Blister (nonthermal), unspecified knee, subsequent encounter', 'Blister (nonthermal), unspecified knee, subsequent encounter');
insert into preparation (complex_name, description) values ('Drown due to falling or jumping from burning fishing boat', 'Drowning and submersion due to falling or jumping from burning fishing boat');
insert into preparation (complex_name, description) values ('Displacement of int fix of right femur, init', 'Displacement of internal fixation device of right femur, initial encounter');
insert into preparation (complex_name, description) values ('Path fx in neopltc dis, oth site, subs for fx w delay heal', 'Pathological fracture in neoplastic disease, other specified site, subsequent encounter for fracture with delayed healing');
insert into preparation (complex_name, description) values ('Displacement of other urinary stents', 'Displacement of other urinary stents');
insert into preparation (complex_name, description) values ('Contusion of lip and oral cavity', 'Contusion of lip and oral cavity');
insert into preparation (complex_name, description) values ('Unsp mtrcy rider inj in clsn w statnry object nontraf, sqla', 'Unspecified motorcycle rider injured in collision with fixed or stationary object in nontraffic accident, sequela');
insert into preparation (complex_name, description) values ('Unsp inj unsp blood vess at ank/ft level, left leg, subs', 'Unspecified injury of unspecified blood vessel at ankle and foot level, left leg, subsequent encounter');
insert into preparation (complex_name, description) values ('Unsp inj femor vein at hip and thi lev, unsp leg, sequela', 'Unspecified injury of femoral vein at hip and thigh level, unspecified leg, sequela');
insert into preparation (complex_name, description) values ('Premature separation of placenta, unsp, third trimester', 'Premature separation of placenta, unspecified, third trimester');
insert into preparation (complex_name, description) values ('Contusion of right middle finger w damage to nail, init', 'Contusion of right middle finger with damage to nail, initial encounter');
insert into preparation (complex_name, description) values ('Incmpl rotatr-cuff tear/ruptr of unsp shoulder, not trauma', 'Incomplete rotator cuff tear or rupture of unspecified shoulder, not specified as traumatic');
insert into preparation (complex_name, description) values ('Unspecified keratitis', 'Unspecified keratitis');
insert into preparation (complex_name, description) values ('Other inflammatory disorders of penis', 'Other inflammatory disorders of penis');
insert into preparation (complex_name, description) values ('Inj unsp musc/fasc/tend at forearm level, unsp arm, sequela', 'Other injury of unspecified muscles, fascia and tendons at forearm level, unspecified arm, sequela');
insert into preparation (complex_name, description) values ('Hereditary nephropathy, not elsewhere classified', 'Hereditary nephropathy, not elsewhere classified');
insert into preparation (complex_name, description) values ('Unspecified injury of deep palmar arch of right hand', 'Unspecified injury of deep palmar arch of right hand');
insert into preparation (complex_name, description) values ('Greenstick fx shaft of rad, unsp arm, subs for fx w nonunion', 'Greenstick fracture of shaft of radius, unspecified arm, subsequent encounter for fracture with nonunion');
insert into preparation (complex_name, description) values ('Burn of first degree of lower leg', 'Burn of first degree of lower leg');
insert into preparation (complex_name, description) values ('Contusion of heart, unsp with or without hemopericardium', 'Contusion of heart, unspecified with or without hemopericardium');
insert into preparation (complex_name, description) values ('Adverse effect of unspecified narcotics, sequela', 'Adverse effect of unspecified narcotics, sequela');
insert into preparation (complex_name, description) values ('Malignant neoplasm of unspecified conjunctiva', 'Malignant neoplasm of unspecified conjunctiva');
insert into preparation (complex_name, description) values ('Poisn by analeptics and opioid receptor antag, acc, sequela', 'Poisoning by analeptics and opioid receptor antagonists, accidental (unintentional), sequela');
insert into preparation (complex_name, description) values ('Retinopathy of prematurity, stage 5', 'Retinopathy of prematurity, stage 5');
insert into preparation (complex_name, description) values ('Adverse effect of other antidysrhythmic drugs, init encntr', 'Adverse effect of other antidysrhythmic drugs, initial encounter');
insert into preparation (complex_name, description) values ('Other specified injuries of right foot', 'Other specified injuries of right foot');
insert into preparation (complex_name, description) values ('Unspecified open wound, right lower leg, initial encounter', 'Unspecified open wound, right lower leg, initial encounter');
insert into preparation (complex_name, description) values ('Toxic effect of ingested mushrooms, undetermined, sequela', 'Toxic effect of ingested mushrooms, undetermined, sequela');
insert into preparation (complex_name, description) values ('Inj superficial vein at shldr/up arm, left arm, init', 'Other specified injury of superficial vein at shoulder and upper arm level, left arm, initial encounter');
insert into preparation (complex_name, description) values ('Nondisp oblique fracture of shaft of unsp radius, sequela', 'Nondisplaced oblique fracture of shaft of unspecified radius, sequela');
insert into preparation (complex_name, description) values ('Burn 3rd deg mu sites of unsp lower limb, ex ank/ft, init', 'Burn of third degree of multiple sites of unspecified lower limb, except ankle and foot, initial encounter');
insert into preparation (complex_name, description) values ('Obstetric pyemic and septic embolism', 'Obstetric pyemic and septic embolism');
insert into preparation (complex_name, description) values ('Unsp physeal fracture of lower end of ulna, unspecified arm', 'Unspecified physeal fracture of lower end of ulna, unspecified arm');
insert into preparation (complex_name, description) values ('Corrosion of unsp degree of back of right hand, init encntr', 'Corrosion of unspecified degree of back of right hand, initial encounter');
insert into preparation (complex_name, description) values ('Injury of femoral vein at hip and thigh level', 'Injury of femoral vein at hip and thigh level');
insert into preparation (complex_name, description) values ('Displ avuls fx tuberosity of r calcaneus, 7thK', 'Displaced avulsion fracture of tuberosity of right calcaneus, subsequent encounter for fracture with nonunion');
insert into preparation (complex_name, description) values ('Other disorders of globe', 'Other disorders of globe');
insert into preparation (complex_name, description) values ('Unsp motorcycle rider injured in collision w oth mv nontraf', 'Unspecified motorcycle rider injured in collision with other motor vehicles in nontraffic accident');
insert into preparation (complex_name, description) values ('Salicylates', 'Poisoning by, adverse effect of and underdosing of other salicylates');
insert into preparation (complex_name, description) values ('Corrosion of third degree of shldr/up lmb, except wrs/hnd', 'Corrosion of third degree of shoulder and upper limb, except wrist and hand');
insert into preparation (complex_name, description) values ('Corrosion of unsp degree of right upper arm, init encntr', 'Corrosion of unspecified degree of right upper arm, initial encounter');
insert into preparation (complex_name, description) values ('Prsn brd/alit a 3-whl mv injured in clsn w pedl cyc, sequela', 'Person boarding or alighting a three-wheeled motor vehicle injured in collision with pedal cycle, sequela');
insert into preparation (complex_name, description) values ('Nondisp spiral fx shaft of l fibula, 7thK', 'Nondisplaced spiral fracture of shaft of left fibula, subsequent encounter for closed fracture with nonunion');
insert into preparation (complex_name, description) values ('Athscl nonbiol bypass of the extrm w intrmt claud, right leg', 'Atherosclerosis of nonbiological bypass graft(s) of the extremities with intermittent claudication, right leg');
insert into preparation (complex_name, description) values ('Fracture of oth skull and facial bones, right side, 7thG', 'Fracture of other specified skull and facial bones, right side, subsequent encounter for fracture with delayed healing');
insert into preparation (complex_name, description) values ('Osteochondrosis (juvenile) of carpal lunate, right hand', 'Osteochondrosis (juvenile) of carpal lunate [Kienbock], right hand');
insert into preparation (complex_name, description) values ('Displ bicondylar fx l tibia, subs for clos fx w routn heal', 'Displaced bicondylar fracture of left tibia, subsequent encounter for closed fracture with routine healing');
insert into preparation (complex_name, description) values ('Pasngr in 3-whl mv injured in nonclsn trnsp accident in traf', 'Passenger in three-wheeled motor vehicle injured in noncollision transport accident in traffic accident');
insert into preparation (complex_name, description) values ('Lacerat flexor musc/fasc/tend at forarm lv, unsp arm, sqla', 'Laceration of other flexor muscle, fascia and tendon at forearm level, unspecified arm, sequela');
insert into preparation (complex_name, description) values ('Toxic effect of lacrimogenic gas', 'Toxic effect of lacrimogenic gas');
insert into preparation (complex_name, description) values ('Unsp pre-existing hypertension compl preg/chldbrth', 'Unspecified pre-existing hypertension complicating pregnancy, childbirth and the puerperium');
insert into preparation (complex_name, description) values ('Varicose veins of lower extremity in the puerperium', 'Varicose veins of lower extremity in the puerperium');
insert into preparation (complex_name, description) values ('Toxic effect of contact with venomous frog', 'Toxic effect of contact with venomous frog');
insert into preparation (complex_name, description) values ('Brown-Sequard syndrome at C5 level of cervical spinal cord', 'Brown-Sequard syndrome at C5 level of cervical spinal cord');
insert into preparation (complex_name, description) values ('Retinal detachment with single break', 'Retinal detachment with single break');
insert into preparation (complex_name, description) values ('Alcohol use complicating pregnancy, third trimester', 'Alcohol use complicating pregnancy, third trimester');
insert into preparation (complex_name, description) values ('Syphilis complicating pregnancy, unspecified trimester', 'Syphilis complicating pregnancy, unspecified trimester');
insert into preparation (complex_name, description) values ('Encounter for routine child health exam w abnormal findings', 'Encounter for routine child health examination with abnormal findings');
insert into preparation (complex_name, description) values ('Pedl cyc driver inj in clsn w statnry object in traf, sqla', 'Pedal cycle driver injured in collision with fixed or stationary object in traffic accident, sequela');
insert into preparation (complex_name, description) values ('Pasngr on bus injured in clsn w nonmtr vehicle in traf, subs', 'Passenger on bus injured in collision with other nonmotor vehicle in traffic accident, subsequent encounter');
insert into preparation (complex_name, description) values ('Nondisp spiral fx shaft of rad, l arm, 7thF', 'Nondisplaced spiral fracture of shaft of radius, left arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into preparation (complex_name, description) values ('Nondisp commnt fx shaft of r fibula, 7thE', 'Nondisplaced comminuted fracture of shaft of right fibula, subsequent encounter for open fracture type I or II with routine healing');
insert into preparation (complex_name, description) values ('Path fx in neopltc disease, pelvis, subs for fx w malunion', 'Pathological fracture in neoplastic disease, pelvis, subsequent encounter for fracture with malunion');
insert into preparation (complex_name, description) values ('Contact with liquid air, initial encounter', 'Contact with liquid air, initial encounter');
insert into preparation (complex_name, description) values ('Struck by golf club', 'Struck by golf club');
insert into preparation (complex_name, description) values ('Acute infarction of intestine, part unspecified', 'Acute infarction of intestine, part unspecified');
insert into preparation (complex_name, description) values ('Displ transverse fx shaft of unsp fibula, 7thM', 'Displaced transverse fracture of shaft of unspecified fibula, subsequent encounter for open fracture type I or II with nonunion');
insert into preparation (complex_name, description) values ('Nondisplaced osteochondral fracture of right patella, init', 'Nondisplaced osteochondral fracture of right patella, initial encounter for closed fracture');
insert into preparation (complex_name, description) values ('Unsp fx low end r femr, 7thJ', 'Unspecified fracture of lower end of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into preparation (complex_name, description) values ('Unspecified physeal fx unspecified calcaneus, sequela', 'Unspecified physeal fracture of unspecified calcaneus, sequela');
insert into preparation (complex_name, description) values ('Charcot''s joint, left ankle and foot', 'Charcot''s joint, left ankle and foot');
insert into preparation (complex_name, description) values ('Puncture wound without foreign body, unsp foot, sequela', 'Puncture wound without foreign body, unspecified foot, sequela');
insert into preparation (complex_name, description) values ('Disp fx of head of unsp rad, 7thN', 'Displaced fracture of head of unspecified radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion');
insert into preparation (complex_name, description) values ('Patient''s noncompliance with dietary regimen', 'Patient''s noncompliance with dietary regimen');
insert into preparation (complex_name, description) values ('Counseling for family member of drug abuser', 'Counseling for family member of drug abuser');
insert into preparation (complex_name, description) values ('Breakdown (mechanical) of intraocular lens, sequela', 'Breakdown (mechanical) of intraocular lens, sequela');
insert into preparation (complex_name, description) values ('Mycosis fungoides, lymph nodes of head, face, and neck', 'Mycosis fungoides, lymph nodes of head, face, and neck');
insert into preparation (complex_name, description) values ('Encounter for screening for malignant neoplasm of ovary', 'Encounter for screening for malignant neoplasm of ovary');
insert into preparation (complex_name, description) values ('Open bite of lip and oral cavity', 'Open bite of lip and oral cavity');
insert into preparation (complex_name, description) values ('Laceration with foreign body of right buttock, subs encntr', 'Laceration with foreign body of right buttock, subsequent encounter');
insert into preparation (complex_name, description) values ('Nondisp seg fx shaft of rad, r arm, 7thP', 'Nondisplaced segmental fracture of shaft of radius, right arm, subsequent encounter for closed fracture with malunion');
insert into preparation (complex_name, description) values ('Injury of optic nerve', 'Injury of optic nerve');
insert into preparation (complex_name, description) values ('Fall through floor, sequela', 'Fall through floor, sequela');
insert into preparation (complex_name, description) values ('Fracture of unspecified metatarsal bone(s)', 'Fracture of unspecified metatarsal bone(s)');
insert into preparation (complex_name, description) values ('Scotoma of blind spot area, right eye', 'Scotoma of blind spot area, right eye');
insert into preparation (complex_name, description) values ('Foreign body granuloma of soft tissue, NEC, unsp upper arm', 'Foreign body granuloma of soft tissue, not elsewhere classified, unspecified upper arm');
insert into preparation (complex_name, description) values ('Sublux of distal interphaln joint of l rng fngr, sequela', 'Subluxation of distal interphalangeal joint of left ring finger, sequela');
insert into preparation (complex_name, description) values ('Toxic effect of benzene, assault, sequela', 'Toxic effect of benzene, assault, sequela');
insert into preparation (complex_name, description) values ('Sltr-haris Type IV physl fx upper end rad, right arm, sqla', 'Salter-Harris Type IV physeal fracture of upper end of radius, right arm, sequela');
insert into preparation (complex_name, description) values ('Unsp dislocation of unspecified shoulder joint, init encntr', 'Unspecified dislocation of unspecified shoulder joint, initial encounter');
insert into preparation (complex_name, description) values ('Displ commnt fx shaft of r femr, 7thF', 'Displaced comminuted fracture of shaft of right femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing');
insert into preparation (complex_name, description) values ('Nondisplaced Maisonneuve''s fracture of unsp leg, sequela', 'Nondisplaced Maisonneuve''s fracture of unspecified leg, sequela');
insert into preparation (complex_name, description) values ('Toxic effect of corrosv acids and acid-like substnc, slf-hrm', 'Toxic effect of corrosive acids and acid-like substances, intentional self-harm');
insert into preparation (complex_name, description) values ('Scotoma involving central area, unspecified eye', 'Scotoma involving central area, unspecified eye');
insert into preparation (complex_name, description) values ('Orthostatic hypotension', 'Orthostatic hypotension');
insert into preparation (complex_name, description) values ('Postdysenteric arthropathy, right hand', 'Postdysenteric arthropathy, right hand');
insert into preparation (complex_name, description) values ('Sedatv/hyp/anxiolytc use, unsp w withdrawal, unsp', 'Sedative, hypnotic or anxiolytic use, unspecified with withdrawal, unspecified');
insert into preparation (complex_name, description) values ('Opioid dependence with unspecified opioid-induced disorder', 'Opioid dependence with unspecified opioid-induced disorder');
insert into preparation (complex_name, description) values ('Intvrt disc stenosis of neural canal of pelvic region', 'Intervertebral disc stenosis of neural canal of pelvic region');
insert into preparation (complex_name, description) values ('Osteochondritis dissecans, unspecified hip', 'Osteochondritis dissecans, unspecified hip');
insert into preparation (complex_name, description) values ('Nondisp fx of med cuneiform of l ft, subs for fx w nonunion', 'Nondisplaced fracture of medial cuneiform of left foot, subsequent encounter for fracture with nonunion');
insert into preparation (complex_name, description) values ('Adverse effect of opium', 'Adverse effect of opium');
insert into preparation (complex_name, description) values ('Other vitamin deficiencies', 'Other vitamin deficiencies');
insert into preparation (complex_name, description) values ('Insect bite (nonvenomous), unspecified hip, subs encntr', 'Insect bite (nonvenomous), unspecified hip, subsequent encounter');
insert into preparation (complex_name, description) values ('Toxic effect of herbicides and fungicides, self-harm', 'Toxic effect of herbicides and fungicides, intentional self-harm');
insert into preparation (complex_name, description) values ('Toxic effect of halogenated insecticides, undetermined', 'Toxic effect of halogenated insecticides, undetermined');
insert into preparation (complex_name, description) values ('Laceration w fb of unsp eyelid and periocular area, init', 'Laceration with foreign body of unspecified eyelid and periocular area, initial encounter');
insert into preparation (complex_name, description) values ('Unspecified pre-eclampsia, complicating the puerperium', 'Unspecified pre-eclampsia, complicating the puerperium');
insert into preparation (complex_name, description) values ('Muscle wasting and atrophy, NEC, right lower leg', 'Muscle wasting and atrophy, not elsewhere classified, right lower leg');
insert into preparation (complex_name, description) values ('Stricture and stenosis of cervix uteri', 'Stricture and stenosis of cervix uteri');
insert into preparation (complex_name, description) values ('Sprain of anterior cruciate ligament of left knee, subs', 'Sprain of anterior cruciate ligament of left knee, subsequent encounter');
insert into preparation (complex_name, description) values ('Nondisp fx of olecran pro w intartic extn unsp ulna, 7thQ', 'Nondisplaced fracture of olecranon process with intraarticular extension of unspecified ulna, subsequent encounter for open fracture type I or II with malunion');
insert into preparation (complex_name, description) values ('Oth soft tissue disord related to use/pressure of shoulder', 'Other soft tissue disorders related to use, overuse and pressure of shoulder');
insert into preparation (complex_name, description) values ('Diffuse traumatic brain injury', 'Diffuse traumatic brain injury');
insert into preparation (complex_name, description) values ('Vomiting of pregnancy, unspecified', 'Vomiting of pregnancy, unspecified');
insert into preparation (complex_name, description) values ('Underdosing of analeptics and opioid receptor antagonists', 'Underdosing of analeptics and opioid receptor antagonists');
insert into preparation (complex_name, description) values ('Displaced bimalleol fx l low leg, init for opn fx type I/2', 'Displaced bimalleolar fracture of left lower leg, initial encounter for open fracture type I or II');
insert into preparation (complex_name, description) values ('Unspecified subluxation of unspecified finger, init encntr', 'Unspecified subluxation of unspecified finger, initial encounter');
insert into preparation (complex_name, description) values ('Strain of unsp musc/tend at lower leg level, left leg', 'Strain of unspecified muscle(s) and tendon(s) at lower leg level, left leg');
insert into preparation (complex_name, description) values ('Superficial foreign body, left thigh', 'Superficial foreign body, left thigh');
insert into preparation (complex_name, description) values ('Acquired atrophy of right fallopian tube', 'Acquired atrophy of right fallopian tube');
insert into preparation (complex_name, description) values ('Other gender identity disorders', 'Other gender identity disorders');
insert into preparation (complex_name, description) values ('Fracture of right shoulder girdle, part unsp, init', 'Fracture of right shoulder girdle, part unspecified, initial encounter for closed fracture');
insert into preparation (complex_name, description) values ('Traumatic rupture of unspecified ligament of left wrist', 'Traumatic rupture of unspecified ligament of left wrist');
insert into preparation (complex_name, description) values ('Nondisp fx of proximal phalanx of l mid finger, sequela', 'Nondisplaced fracture of proximal phalanx of left middle finger, sequela');
insert into preparation (complex_name, description) values ('Driver of hv veh inj in clsn w 2/3-whl mv nontraf, sequela', 'Driver of heavy transport vehicle injured in collision with two- or three-wheeled motor vehicle in nontraffic accident, sequela');
insert into preparation (complex_name, description) values ('Fall due to bumping against object', 'Fall due to bumping against object');
insert into preparation (complex_name, description) values ('Laceration without foreign body of unsp buttock, init encntr', 'Laceration without foreign body of unspecified buttock, initial encounter');
insert into preparation (complex_name, description) values ('Nondisp commnt fx unsp patella, 7thM', 'Nondisplaced comminuted fracture of unspecified patella, subsequent encounter for open fracture type I or II with nonunion');
insert into preparation (complex_name, description) values ('Open bite, left foot', 'Open bite, left foot');
insert into preparation (complex_name, description) values ('Nondisp fx of glenoid cav of scapula, unsp shldr, 7thG', 'Nondisplaced fracture of glenoid cavity of scapula, unspecified shoulder, subsequent encounter for fracture with delayed healing');
insert into preparation (complex_name, description) values ('Nondisp fx of base of unspecified metacarpal bone, sequela', 'Nondisplaced fracture of base of unspecified metacarpal bone, sequela');
insert into preparation (complex_name, description) values ('Injury of radial nerve at wrs/hnd lv of unsp arm, init', 'Injury of radial nerve at wrist and hand level of unspecified arm, initial encounter');
insert into preparation (complex_name, description) values ('Oth intartic fx low end r rad, 7thJ', 'Other intraarticular fracture of lower end of right radius, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing');
insert into preparation (complex_name, description) values ('Assault by antipersonnel bomb', 'Assault by antipersonnel bomb');
insert into preparation (complex_name, description) values ('Rheumatoid polyneuropathy w rheumatoid arthritis of shoulder', 'Rheumatoid polyneuropathy with rheumatoid arthritis of shoulder');
insert into preparation (complex_name, description) values ('Transient global amnesia', 'Transient global amnesia');
insert into preparation (complex_name, description) values ('Major laceration of right carotid artery, initial encounter', 'Major laceration of right carotid artery, initial encounter');
insert into preparation (complex_name, description) values ('Injury of muscle, fascia and tendon at hip and thigh level', 'Injury of muscle, fascia and tendon at hip and thigh level');
insert into preparation (complex_name, description) values ('Burn of second degree of right hand, unsp site, sequela', 'Burn of second degree of right hand, unspecified site, sequela');
insert into preparation (complex_name, description) values ('Drown d/t being washed ovrbrd from oth power wtrcrft, sqla', 'Drowning and submersion due to being washed overboard from other powered watercraft, sequela');
insert into preparation (complex_name, description) values ('Open bite of r frnt wl of thorax w/o penet thor cavity, init', 'Open bite of right front wall of thorax without penetration into thoracic cavity, initial encounter');
insert into preparation (complex_name, description) values ('Supervision of young multigravida, second trimester', 'Supervision of young multigravida, second trimester');
insert into preparation (complex_name, description) values ('Other anterior subluxation of left hip, sequela', 'Other anterior subluxation of left hip, sequela');
insert into preparation (complex_name, description) values ('Oth nondisp fx of base of first MC bone, right hand, sequela', 'Other nondisplaced fracture of base of first metacarpal bone, right hand, sequela');
insert into preparation (complex_name, description) values ('Malignant neoplasm of parotid gland', 'Malignant neoplasm of parotid gland');
insert into preparation (complex_name, description) values ('Corrosion of unspecified degree of right axilla, subs encntr', 'Corrosion of unspecified degree of right axilla, subsequent encounter');
