insert into training (name, description) values ('Kuvalis, Pfeffer and Ruecker', 'Complete traumatic amputation at hip joint');
insert into training (name, description) values ('Upton-McLaughlin', 'Underdosing of antigonadotrophins, antiestrogens, antiandrogens, not elsewhere classified, subsequent encounter');
insert into training (name, description) values ('Koch, Simonis and Crona', 'Fracture of unspecified phalanx of unspecified finger, initial encounter for closed fracture');
insert into training (name, description) values ('Kiehn, Connelly and Cartwright', 'Other fracture of fifth cervical vertebra');
insert into training (name, description) values ('Von Group', 'Displacement of infusion catheter');
insert into training (name, description) values ('Keeling, Quitzon and Barton', 'Open bite of unspecified cheek and temporomandibular area, subsequent encounter');
insert into training (name, description) values ('Spencer, Doyle and Witting', 'Hereditary ataxia');
insert into training (name, description) values ('Hilpert LLC', 'War operations involving combat using blunt or piercing object, civilian');
insert into training (name, description) values ('Littel-Aufderhar', 'Pathological fracture in neoplastic disease, unspecified humerus, subsequent encounter for fracture with malunion');
insert into training (name, description) values ('Wiza Group', 'Occupant of streetcar injured in unspecified traffic accident, initial encounter');
insert into training (name, description) values ('Kerluke-McLaughlin', 'Toxic effect of lacrimogenic gas, undetermined, subsequent encounter');
insert into training (name, description) values ('Kunze, Schimmel and Cartwright', 'Car driver injured in collision with car, pick-up truck or van in nontraffic accident');
insert into training (name, description) values ('Wiza, Welch and Wintheiser', 'Nondisplaced fracture of lateral end of unspecified clavicle, subsequent encounter for fracture with malunion');
insert into training (name, description) values ('Bauch, Hoeger and Rogahn', 'Hypoxic ischemic encephalopathy [HIE], unspecified');
insert into training (name, description) values ('Swift and Sons', 'Complete placenta previa NOS or without hemorrhage, first trimester');
insert into training (name, description) values ('Wilkinson Group', 'Puncture wound without foreign body of unspecified breast, subsequent encounter');
insert into training (name, description) values ('Jerde, Boehm and Miller', 'Open wound of unspecified part of head');
insert into training (name, description) values ('Daugherty LLC', 'Displaced fracture of shaft of second metacarpal bone, left hand, initial encounter for closed fracture');
insert into training (name, description) values ('McKenzie-Pagac', 'Subluxation of L2/L3 lumbar vertebra, initial encounter');
insert into training (name, description) values ('Christiansen-Herman', 'Unspecified injury of extensor muscle, fascia and tendon of right little finger at wrist and hand level');
insert into training (name, description) values ('Toy Inc', 'Adverse effect of other drugs acting on muscles, initial encounter');
insert into training (name, description) values ('Powlowski, Nienow and Parisian', 'Laceration with foreign body of unspecified toe(s) with damage to nail, sequela');
insert into training (name, description) values ('Yundt, Littel and Crona', 'Other chronic hematogenous osteomyelitis, radius and ulna');
insert into training (name, description) values ('Kessler-Hoppe', 'Necrotizing enterocolitis, unspecified');
insert into training (name, description) values ('Funk LLC', 'Lead-induced chronic gout, unspecified shoulder');
insert into training (name, description) values ('McLaughlin, Kautzer and Carter', 'Nondisplaced fracture of posterior wall of left acetabulum, sequela');
insert into training (name, description) values ('Kuhic Group', 'Subluxation of metacarpophalangeal joint of right middle finger, initial encounter');
insert into training (name, description) values ('Hodkiewicz LLC', 'Therapeutic (nonsurgical) and rehabilitative anesthesiology devices associated with adverse incidents');
insert into training (name, description) values ('Beier and Sons', 'Other soft tissue disorders related to use, overuse and pressure, left hand');
insert into training (name, description) values ('Watsica and Sons', 'Unspecified traumatic displaced spondylolisthesis of seventh cervical vertebra, sequela');
insert into training (name, description) values ('Boyer-Mueller', 'Puncture wound without foreign body of left ring finger without damage to nail, initial encounter');
insert into training (name, description) values ('Ruecker, McClure and Hansen', 'Explosion on board sailboat, subsequent encounter');
insert into training (name, description) values ('Dickens-Hermann', 'Autoimmune lymphoproliferative syndrome [ALPS]');
insert into training (name, description) values ('Cruickshank, McGlynn and Bergnaum', 'Pedestrian with other conveyance injured in collision with pedal cycle, unspecified whether traffic or nontraffic accident, subsequent encounter');
insert into training (name, description) values ('Baumbach-Cruickshank', 'Pathological fracture in other disease, unspecified shoulder');
insert into training (name, description) values ('Hegmann, Daniel and Abshire', 'Partial traumatic amputation at level between left shoulder and elbow');
insert into training (name, description) values ('Block and Sons', 'Other rupture of muscle (nontraumatic), unspecified lower leg');
insert into training (name, description) values ('Dach, Macejkovic and Fay', 'Poisoning by butyrophenone and thiothixene neuroleptics, accidental (unintentional)');
insert into training (name, description) values ('Thiel-Wuckert', 'Poisoning by tricyclic antidepressants, undetermined, subsequent encounter');
insert into training (name, description) values ('Stokes LLC', 'Unspecified superficial injury of unspecified ankle, sequela');
insert into training (name, description) values ('O''Kon, Upton and Rohan', 'Infection and inflammatory reaction due to ventricular intracranial (communicating) shunt, sequela');
insert into training (name, description) values ('D''Amore and Sons', 'Open bite of abdominal wall, right lower quadrant with penetration into peritoneal cavity');
insert into training (name, description) values ('Kuhlman, Sawayn and Luettgen', 'Drug or chemical induced diabetes mellitus with severe nonproliferative diabetic retinopathy without macular edema, unspecified eye');
insert into training (name, description) values ('Kshlerin LLC', 'Toxic effect of strychnine and its salts, assault, initial encounter');
insert into training (name, description) values ('Osinski Inc', 'Open bite of right thumb without damage to nail, sequela');
insert into training (name, description) values ('Johns-Hilpert', 'Bilateral femoral hernia, with obstruction, without gangrene, not specified as recurrent');
insert into training (name, description) values ('Roberts and Sons', 'Subluxation of tarsometatarsal joint of left foot, initial encounter');
insert into training (name, description) values ('Nikolaus, Lowe and Kirlin', 'Major laceration of right pulmonary blood vessels, initial encounter');
insert into training (name, description) values ('Gottlieb, Pfannerstill and Anderson', 'Nondisplaced fracture of right ulna styloid process, subsequent encounter for closed fracture with delayed healing');
insert into training (name, description) values ('King Group', 'Sprain of metacarpophalangeal joint of left little finger, subsequent encounter');
insert into training (name, description) values ('Lubowitz, Blanda and Jerde', 'Age-related osteoporosis with current pathological fracture, right humerus, sequela');
insert into training (name, description) values ('Wolf and Sons', 'Nondisplaced fracture of unspecified ulna styloid process, subsequent encounter for open fracture type I or II with nonunion');
insert into training (name, description) values ('Metz-Adams', 'Physical abuse, confirmed');
insert into training (name, description) values ('Boyle, Corkery and Smith', 'Toxic effect of venom of black widow spider, accidental (unintentional)');
insert into training (name, description) values ('MacGyver, Leannon and Baumbach', 'Laceration of muscle and tendon of long extensor muscle of toe at ankle and foot level');
insert into training (name, description) values ('Emmerich-Considine', 'Other reactive arthropathies, unspecified site');
insert into training (name, description) values ('Brown, Gottlieb and Armstrong', 'Skeletal fluorosis, unspecified hand');
insert into training (name, description) values ('Kozey and Sons', 'Corrosion of first degree of nose (septum), sequela');
insert into training (name, description) values ('Feil-Sipes', 'Other fracture of shaft of radius, left arm, subsequent encounter for closed fracture with routine healing');
insert into training (name, description) values ('Treutel-Kuhn', 'Drug-induced headache, not elsewhere classified, not intractable');
insert into training (name, description) values ('Christiansen Group', 'Poisoning by unspecified psychostimulants, accidental (unintentional), sequela');
insert into training (name, description) values ('Herman, Stiedemann and O''Keefe', 'Corrosion of second degree of other site of trunk, sequela');
insert into training (name, description) values ('Bradtke LLC', 'Other specified injury of left renal artery, subsequent encounter');
insert into training (name, description) values ('Mills LLC', 'Displaced fracture of trapezoid [smaller multangular], unspecified wrist');
insert into training (name, description) values ('Lind, Zieme and Will', 'Other specified intracranial injury with loss of consciousness of 6 hours to 24 hours, initial encounter');
insert into training (name, description) values ('O''Kon-Harber', 'Anterior spinal artery compression syndromes, occipito-atlanto-axial region');
insert into training (name, description) values ('Hegmann Group', 'Nondisplaced spiral fracture of shaft of right femur, subsequent encounter for closed fracture with delayed healing');
insert into training (name, description) values ('Beatty-Stoltenberg', 'Displaced fracture of body of left talus, subsequent encounter for fracture with routine healing');
insert into training (name, description) values ('Murazik Group', 'Other fracture of upper end of right ulna, subsequent encounter for open fracture type I or II with delayed healing');
insert into training (name, description) values ('Gislason-Miller', 'Unspecified car occupant injured in collision with heavy transport vehicle or bus in nontraffic accident');
insert into training (name, description) values ('Towne, Dibbert and Zieme', 'Other acariasis');
insert into training (name, description) values ('Emmerich, Hand and Adams', 'Displaced bimalleolar fracture of left lower leg, sequela');
insert into training (name, description) values ('Padberg LLC', 'Nondisplaced fracture of lateral end of unspecified clavicle, initial encounter for closed fracture');
insert into training (name, description) values ('Ebert Group', 'Displaced fracture of coracoid process, right shoulder');
insert into training (name, description) values ('Gerlach-Gorczany', 'Benign neoplasm of brain, supratentorial');
insert into training (name, description) values ('Pouros Group', 'Traumatic rupture of palmar ligament of left little finger at metacarpophalangeal and interphalangeal joint');
insert into training (name, description) values ('Wilderman-Hansen', 'Other paralytic syndrome following nontraumatic intracerebral hemorrhage');
insert into training (name, description) values ('Hilll, Thiel and Pfeffer', 'Hemiplegic migraine, not intractable');
insert into training (name, description) values ('McDermott-Tromp', 'Toxic effect of contact with other venomous amphibian, intentional self-harm, subsequent encounter');
insert into training (name, description) values ('Nitzsche, Kris and Ondricka', 'Crushing injury of unspecified elbow, subsequent encounter');
insert into training (name, description) values ('Daniel Group', 'Total perforations of tympanic membrane, left ear');
insert into training (name, description) values ('Gottlieb-Wilkinson', 'Unspecified fracture of facial bones, initial encounter for closed fracture');
insert into training (name, description) values ('Schuppe and Sons', 'Fracture of unspecified phalanx of left little finger, subsequent encounter for fracture with routine healing');
insert into training (name, description) values ('Hoppe-Johnson', 'Striking against or struck by front passenger side automobile airbag, initial encounter');
insert into training (name, description) values ('Littel-Botsford', 'Toxic effect of unspecified snake venom, intentional self-harm');
insert into training (name, description) values ('Haag, Rutherford and Goyette', 'Osteonecrosis in diseases classified elsewhere, ankle and foot');
insert into training (name, description) values ('Paucek LLC', 'Open wound of unspecified external genital organs');
insert into training (name, description) values ('Lynch Inc', 'Traumatic arthropathy, left ankle and foot');
insert into training (name, description) values ('Bechtelar-Jaskolski', 'Adverse effect of unspecified antidepressants, initial encounter');
insert into training (name, description) values ('Farrell, Hoppe and McDermott', 'Dislocation of distal interphalangeal joint of left middle finger, initial encounter');
insert into training (name, description) values ('Shields Inc', 'Legal intervention involving other sharp objects, bystander injured, sequela');
insert into training (name, description) values ('Walter-Fahey', 'Fall from burning building or structure in controlled fire, sequela');
insert into training (name, description) values ('Wyman-Stanton', 'Displaced fracture of olecranon process without intraarticular extension of unspecified ulna, initial encounter for open fracture type I or II');
insert into training (name, description) values ('Moore LLC', 'Pain disorders related to psychological factors');
insert into training (name, description) values ('Mayert Inc', 'Burn of unspecified degree of unspecified thigh, subsequent encounter');
insert into training (name, description) values ('Stark-Emard', 'Other specified intestinal infections');
insert into training (name, description) values ('Stoltenberg, Schumm and Cormier', 'Pregnancy related exhaustion and fatigue, second trimester');
insert into training (name, description) values ('Hartmann-Marks', 'Other nondisplaced fracture of base of first metacarpal bone, left hand, subsequent encounter for fracture with nonunion');
insert into training (name, description) values ('Bernhard, Stehr and Stamm', 'Postprocedural cardiac arrest following other surgery');
insert into training (name, description) values ('Bode-Emmerich', 'Complete traumatic amputation of left forearm, level unspecified, subsequent encounter');
