insert into exercise (name, description) values ('Rosenbaum, Dickens and Gorczany', 'Catesbaea L.');
insert into exercise (name, description) values ('Pollich Inc', 'Cardamine flagellifera O.E. Schulz');
insert into exercise (name, description) values ('Larson LLC', 'Astragalus convallarius Greene var. finitimus Barneby');
insert into exercise (name, description) values ('Cruickshank, Kuhic and Boyer', 'Rhamnus lanceolata Pursh');
insert into exercise (name, description) values ('Walker and Sons', 'Chrysothamnus viscidiflorus (Hook.) Nutt.');
insert into exercise (name, description) values ('Champlin, Wilkinson and Feeney', 'Symphyotrichum foliaceum (Lindl. ex DC.) G.L. Nesom var. canbyi (A. Gray) G.L. Nesom');
insert into exercise (name, description) values ('Jerde Group', 'Solidago petiolaris Aiton var. petiolaris');
insert into exercise (name, description) values ('Hauck-Borer', 'Mycomicrothelia capitosa (Krempelh.) D. Hawksw.');
insert into exercise (name, description) values ('Treutel Inc', '×Agroelymus adamsii Rouss.');
insert into exercise (name, description) values ('Torphy Inc', 'Myrsine mezii Hosaka');
insert into exercise (name, description) values ('Hansen, Monahan and Sauer', 'Camissonia minor (A. Nelson) P.H. Raven');
insert into exercise (name, description) values ('Will, Feest and Lehner', 'Calystegia malacophylla (Greene) Munz');
insert into exercise (name, description) values ('Gutmann LLC', 'Severinia monophylla (L.) Tanaka [excluded]');
insert into exercise (name, description) values ('Lindgren Inc', 'Monarda punctata L. ssp. punctata var. intermedia (E.M. McClint. & Epling) Waterf.');
insert into exercise (name, description) values ('Fahey, Purdy and Effertz', 'Pectis papposa Harv. & A. Gray var. papposa');
insert into exercise (name, description) values ('Heller, Hills and Smitham', 'Homaliadelphus Dix. & P. Varde');
insert into exercise (name, description) values ('Douglas-Larson', 'Senecio quaylei T.M. Barkley');
insert into exercise (name, description) values ('Lehner-Quitzon', 'Rhabdoweisia crispata (With.) Lindb.');
insert into exercise (name, description) values ('Will, Beier and Bradtke', 'Phlox andicola E.E. Nelson ssp. parvula Wherry');
insert into exercise (name, description) values ('Rolfson-Monahan', 'Psora russellii (Tuck.) A. Schneid.');
insert into exercise (name, description) values ('O''Connell-Stokes', 'Cercis canadensis L. var. mexicana (Rose) M. Hopkins');
insert into exercise (name, description) values ('Kihn, Oberbrunner and Hamill', 'Elaphoglossum herminieri (Bory & Fée) T. Moore');
insert into exercise (name, description) values ('Hermann and Sons', 'Myosotis arvensis (L.) Hill');
insert into exercise (name, description) values ('Jenkins-Hickle', 'Pilophorus vegae Krog');
insert into exercise (name, description) values ('Johnston, White and Sanford', 'Carex specifica L.H. Bailey');
insert into exercise (name, description) values ('Padberg, Kovacek and Feest', 'Silene verecunda S. Watson ssp. platyota (S. Watson) C.L. Hitchc. & Maguire var. platyota (S. Watson) Jeps.');
insert into exercise (name, description) values ('Powlowski LLC', 'Croomia Torr.');
insert into exercise (name, description) values ('Kris-Pouros', 'Astragalus trichopodus (Nutt.) A. Gray');
insert into exercise (name, description) values ('Moore Inc', 'Solidago missouriensis Nutt.');
insert into exercise (name, description) values ('Harris, Osinski and Osinski', 'Ipomopsis spicata (Nutt.) V.E. Grant ssp. spicata');
insert into exercise (name, description) values ('Pagac-Hoppe', 'Diapensia lapponica L.');
insert into exercise (name, description) values ('Mante, Moen and Hauck', 'Myrsine wawraea (Mez) Hosaka');
insert into exercise (name, description) values ('Shanahan and Sons', 'Thelypteris poiteana (Bory) Proctor');
insert into exercise (name, description) values ('Satterfield, Schroeder and Gerhold', 'Neckera douglasii Hook.');
insert into exercise (name, description) values ('Wilkinson-Stehr', 'Melpomense anfractuosa (Kunze ex Klotzsch) A.R. Sm. & R.C. Moran');
insert into exercise (name, description) values ('Schumm-Reilly', 'Eugenia eucalyptoides F. Muell.');
insert into exercise (name, description) values ('Anderson-Feil', 'Rhynchospora berteroi (Spreng.) C.B. Clarke');
insert into exercise (name, description) values ('Cronin-McDermott', 'Rhus michauxii Sarg.');
insert into exercise (name, description) values ('Mayer and Sons', 'Crataegus ×hudsonica Sarg. (pro sp.)');
insert into exercise (name, description) values ('Miller, Lemke and Barton', 'Lasiacis sorghoidea (Desv. ex Ham.) Hitchc. & Chase var. sorghoidea');
insert into exercise (name, description) values ('Abshire-Rosenbaum', 'Linum westii C.M. Rogers');
insert into exercise (name, description) values ('Kassulke, Welch and Will', 'Rubus ortivus (L.H. Bailey) L.H. Bailey');
insert into exercise (name, description) values ('Price-Kulas', 'Arenaria aberrans M.E. Jones');
insert into exercise (name, description) values ('Price-Hoppe', 'Graphina incrustans (Fée) Müll. Arg.');
insert into exercise (name, description) values ('Schaefer-Fritsch', 'Axonopus micay Garcia-Barr.');
insert into exercise (name, description) values ('Watsica-Langosh', 'Solidago hispida Muhl. ex Willd. var. hispida');
insert into exercise (name, description) values ('Berge Inc', 'Achyranthes splendens Mart. ex Moq. var. splendens');
insert into exercise (name, description) values ('Parisian-Boyle', 'Tradescantia subaspera Ker Gawl.');
insert into exercise (name, description) values ('Balistreri, Cormier and Dooley', 'Parmeliopsis (Stizenb.) Nyl.');
insert into exercise (name, description) values ('Dooley, Kunze and Lind', 'Brachionidium sherringii Rolfe');
insert into exercise (name, description) values ('Emmerich-Mayer', 'Carex tetanica Schkuhr');
insert into exercise (name, description) values ('Koelpin-Ankunding', 'Tetramolopium conyzoides (A. Gray) Hillebr.');
insert into exercise (name, description) values ('Kunde Inc', 'Rubus ursinus Cham. & Schltdl. ssp. ursinus var. sirbenus (L.H. Bailey) J.T. Howell');
insert into exercise (name, description) values ('Haag, Runte and Nader', 'Potentilla diversifolia Lehm.');
insert into exercise (name, description) values ('Orn Group', 'Salix ×rubens Schrank (pro sp.)');
insert into exercise (name, description) values ('Pacocha-Fritsch', 'Astragalus conjunctus S. Watson var. conjunctus');
insert into exercise (name, description) values ('Rau-Kilback', 'Berberis wisleyensis Ahrendt');
insert into exercise (name, description) values ('Gerhold-Cassin', 'Chamaesyce berteriana (Balbis ex Spreng.) Millsp.');
insert into exercise (name, description) values ('Bergstrom, Ryan and Kautzer', 'Xanthoparmelia ajoensis (T. Nash) Egan');
insert into exercise (name, description) values ('Torphy, Hilpert and Wisoky', 'Anulocaulis leiosolenus (Torr.) Standl. var. gypsogenus (Waterf.) Spellenb. & Wootten');
insert into exercise (name, description) values ('Will LLC', 'Orbexilum lupinellum (Michx.) Isely');
insert into exercise (name, description) values ('Blick and Sons', 'Asplenium ×herb-wagneri W.C. Taylor & Mohlenbr.');
insert into exercise (name, description) values ('McClure-Hyatt', 'Olsynium douglasii (A. Dietr.) E.P. Bicknell var. inflatum (Suksd.) Cholewa & Douglass M. Hend.');
insert into exercise (name, description) values ('Abshire-Rath', 'Cyanea macrostegia Hillebr. ssp. macrostegia');
insert into exercise (name, description) values ('Harris, Predovic and Grant', 'Cercis L.');
insert into exercise (name, description) values ('Balistreri-Hettinger', 'Penstemon linarioides A. Gray ssp. coloradoensis (A. Nelson) D.D. Keck');
insert into exercise (name, description) values ('Bosco Group', 'Impatiens walleriana Hook. f.');
insert into exercise (name, description) values ('O''Conner LLC', 'Schistidium andreaeopsis (Müll. Hal.) Laz.');
insert into exercise (name, description) values ('Grant LLC', 'Balsamorhiza deltoidea Nutt.');
insert into exercise (name, description) values ('Wehner-Predovic', 'Polystichum imbricans (D.C. Eaton) D.H. Wagner');
insert into exercise (name, description) values ('Brakus-Boehm', 'Artemisia campestris L. ssp. borealis (Pall.) H.M. Hall & Clem. var. wormskioldii (Besser ex Hook.) Cronquist');
insert into exercise (name, description) values ('Olson, Dickens and Koelpin', 'Lecanora mellea W.A. Weber');
insert into exercise (name, description) values ('Tillman-Fritsch', 'Ambrosia ambrosioides (Cav.) Payne');
insert into exercise (name, description) values ('Beer, Sawayn and Wiza', 'Bunias L.');
insert into exercise (name, description) values ('Jerde, Dicki and Connelly', 'Flemingia Roxb. ex W.T. Aiton');
insert into exercise (name, description) values ('Klein-Schuppe', 'Phoenix L.');
insert into exercise (name, description) values ('Towne, Nienow and Treutel', 'Tectaria coriandrifolia (Sw.) Underw.');
insert into exercise (name, description) values ('Lesch-Schinner', 'Dendriscocaulon intricatulum (Nyl.) Henssen');
insert into exercise (name, description) values ('Kulas Group', 'Sparganium emersum Rehmann');
insert into exercise (name, description) values ('Beatty Group', 'Pediomelum verdiense S.L. Welsh & Licher');
insert into exercise (name, description) values ('Wyman-Douglas', 'Ipomoea shumardiana (Torr.) Shinners');
insert into exercise (name, description) values ('Moore Inc', 'Stachys germanica L.');
insert into exercise (name, description) values ('Champlin and Sons', 'Polysporina simplex (Davies) Vezda');
insert into exercise (name, description) values ('Davis, Barton and Koch', 'Pogostemon cablin (Blanco) Benth.');
insert into exercise (name, description) values ('Goodwin-McClure', 'Lloydia serotina (L.) Salisb. ex Rchb. var. serotina');
insert into exercise (name, description) values ('Tromp-Monahan', 'Lupinus diffusus Nutt.');
insert into exercise (name, description) values ('Kirlin Inc', 'Lewisia cotyledon (S. Watson) B.L. Rob. var. heckneri (Morton) Munz');
insert into exercise (name, description) values ('Friesen, Reynolds and Ferry', 'Lycopus americanus Muhl. ex W.P.C. Barton');
insert into exercise (name, description) values ('Dooley and Sons', 'Phaseolus vulgaris L.');
insert into exercise (name, description) values ('Windler LLC', 'Perityle specuicola S.L. Welsh & Neese');
insert into exercise (name, description) values ('Marvin and Sons', 'Sidalcea neomexicana A. Gray');
insert into exercise (name, description) values ('Treutel, Wyman and Witting', 'Heuchera parvifolia Nutt. ex Torr. & A. Gray var. microcarpa Rosend., Butters & Lakela');
insert into exercise (name, description) values ('Zulauf-Nolan', 'Oenothera jamesii Torr. & A. Gray');
insert into exercise (name, description) values ('Kassulke and Sons', 'Cynosciadium DC.');
insert into exercise (name, description) values ('Connelly, Schroeder and Schaefer', 'Passiflora serratodigitata L.');
insert into exercise (name, description) values ('Bartell Inc', 'Androsace chamaejasme Wulfen');
insert into exercise (name, description) values ('Hilpert-Dickens', 'Rhamnus serrata Humb. & Bonpl. ex Schult.');
insert into exercise (name, description) values ('Nader-Lebsack', 'Synthyris ranunculina Pennell');
insert into exercise (name, description) values ('Will-Heidenreich', 'Tortula papillosissima (Copp.) Broth.');
insert into exercise (name, description) values ('Collier, Nienow and Feeney', 'Astragalus hallii A. Gray var. fallax (M.E. Jones) Barneby');
insert into exercise (name, description) values ('Cummerata-DuBuque', 'Primula eximia Greene');
insert into exercise (name, description) values ('Johnson, Bogisich and Shields', 'Chionanthus ligustrinus (Sw.) Pers.');
insert into exercise (name, description) values ('Fritsch Group', 'Echinacea atrorubens Nutt.');
insert into exercise (name, description) values ('Yundt-Treutel', 'Aspicilia verrucigera Hue');
insert into exercise (name, description) values ('Purdy-Ondricka', 'Conostomum Sw.');
insert into exercise (name, description) values ('Glover, Kunze and Schaden', 'Phacelia vallis-mortae J. Voss var. heliophila (J.F. Macbr.) J. Voss');
insert into exercise (name, description) values ('McGlynn Group', 'Ericameria nauseosa (Pall. ex Pursh) G.L. Nesom & Baird ssp. nauseosa var. texensis (L.C. Anderson) G.L. Nesom & Baird');
insert into exercise (name, description) values ('Rosenbaum-Gaylord', 'Pavonia paniculata Cav.');
insert into exercise (name, description) values ('Becker-Conn', 'Lomatium tracyi Mathias & Constance');
insert into exercise (name, description) values ('Smitham Inc', 'Hydrophyllum L.');
insert into exercise (name, description) values ('Ritchie, Hills and Lockman', 'Myosurus nitidus Eastw.');
insert into exercise (name, description) values ('Little, VonRueden and Price', 'Verrucaria degelii R. Sant.');
insert into exercise (name, description) values ('DuBuque Inc', 'Elmera racemosa (S. Watson) Rydb.');
insert into exercise (name, description) values ('O''Kon, Jacobs and Green', 'Artemisia stelleriana Besser');
insert into exercise (name, description) values ('Jaskolski, Metz and Bins', 'Nasturtium microphyllum Boenn. ex Rchb.');
insert into exercise (name, description) values ('Smith-Dibbert', 'Phoradendron villosum (Nutt.) Nutt.');
insert into exercise (name, description) values ('Watsica, Schneider and Rau', 'Croptilon hookerianum (Torr. & A. Gray) House var. validum (Rydb.) E.B. Sm.');
insert into exercise (name, description) values ('Kub-Purdy', 'Amorpha herbacea Walter var. herbacea');
insert into exercise (name, description) values ('Weimann, Lindgren and Zboncak', 'Descurainia incana (Bernh. ex Fisch. & C.A. Mey.) Dorn');
insert into exercise (name, description) values ('Leannon-Trantow', 'Wissadula Medik.');
insert into exercise (name, description) values ('Breitenberg-Pacocha', 'Glyceria melicaria (Michx.) F.T. Hubbard');
insert into exercise (name, description) values ('Doyle Inc', 'Lycopodium venustulum Gaudich. var. venustulum');
insert into exercise (name, description) values ('Adams-Gottlieb', 'Mirabilis expansa (Ruiz & Pav.) Standl.');
insert into exercise (name, description) values ('Homenick LLC', 'Thelomma A. Massal.');
insert into exercise (name, description) values ('Bergstrom-Senger', 'Phoebanthus grandiflorus (Torr. & A. Gray) S.F. Blake');
insert into exercise (name, description) values ('Bauch LLC', 'Peperomia cookiana C. DC.');
insert into exercise (name, description) values ('Haley-Cartwright', 'Amaranthus ×tucsonensis Henrickson');
insert into exercise (name, description) values ('Kohler-Hahn', 'Sibbaldia L.');
insert into exercise (name, description) values ('Hagenes-Spencer', 'Eleocharis tortilis (Link) Schult.');
insert into exercise (name, description) values ('Bosco Group', 'Physalis mollis Nutt. var. variovestita (Waterf.) J.R. Sullivan');
insert into exercise (name, description) values ('Jacobs, Champlin and Baumbach', 'Eleocharis congesta D. Don');
insert into exercise (name, description) values ('Effertz and Sons', 'Carex communis L.H. Bailey var. communis');
insert into exercise (name, description) values ('Bashirian-Veum', 'Calochortus kennedyi Porter');
insert into exercise (name, description) values ('White-Reichel', 'Gardenia volkensii K. Schum.');
insert into exercise (name, description) values ('Mann-Hagenes', 'Sticherus brevipubis (Christ) A.R. Sm.');
insert into exercise (name, description) values ('Stark, Hane and Morar', 'Oxalis L.');
insert into exercise (name, description) values ('Schulist, Haag and Barton', 'Arnica chamissonis Less. ssp. chamissonis var. interior Maguire');
insert into exercise (name, description) values ('Jacobson, Dooley and Ebert', 'Oxytropis splendens Douglas ex Hook.');
insert into exercise (name, description) values ('Smith Group', 'Schoenus L.');
insert into exercise (name, description) values ('Kemmer-Renner', 'Salix delnortensis C.K. Schneid.');
insert into exercise (name, description) values ('Corkery, Lakin and O''Hara', 'Dicranum majus Sm.');
insert into exercise (name, description) values ('Ritchie, Champlin and Botsford', 'Salvinia natans (L.) All.');
insert into exercise (name, description) values ('Littel-Borer', 'Stereocaulon leprocephalum Vain.');
insert into exercise (name, description) values ('King-Weber', 'Lonicera hispidula (Lindl.) Douglas ex Torr. & A. Gray');
insert into exercise (name, description) values ('Weimann-Langworth', 'Rorippa islandica (Oeder) Borbás');
insert into exercise (name, description) values ('White Inc', 'Ixia campanulata Houtt.');
insert into exercise (name, description) values ('Herman-Nikolaus', 'Azolla Lam.');
insert into exercise (name, description) values ('Wuckert Inc', 'Jaffueliobryum raui (Austin) Thér.');
insert into exercise (name, description) values ('Boyle, Kemmer and Jakubowski', 'Argyreia Lour.');
insert into exercise (name, description) values ('Collins LLC', 'Ribes spicatum E. Robson');
insert into exercise (name, description) values ('Hoppe, Blanda and Stark', 'Alsophila R. Br.');
insert into exercise (name, description) values ('Reynolds-Ratke', 'Seymeria pectinata Pursh');
insert into exercise (name, description) values ('Koss, Predovic and Cummings', 'Pentachaeta aurea Nutt. ssp. aurea');
insert into exercise (name, description) values ('Vandervort, Mraz and Gislason', 'Amaranthus fimbriatus (Torr.) Benth. ex S. Watson');
insert into exercise (name, description) values ('Harber-Pollich', 'Aquilegia loriae S.L. Welsh & N.D. Atwood');
insert into exercise (name, description) values ('Buckridge, Barrows and Keeling', 'Arisaema speciosum (Wall.) Mart.');
insert into exercise (name, description) values ('Shields and Sons', 'Eriogonum annuum Nutt.');
insert into exercise (name, description) values ('Grimes, Schultz and Carroll', 'Astrolepis Benham & Windham');
insert into exercise (name, description) values ('Rice, Ziemann and Prosacco', 'Houstonia purpurea L. var. calycosa A. Gray');
insert into exercise (name, description) values ('Rutherford, Torphy and Barton', 'Chrysanthemum L.');
insert into exercise (name, description) values ('Heathcote, Beier and Trantow', 'Mimulus pulsiferae A. Gray');
insert into exercise (name, description) values ('Bins Inc', 'Ribes rotundifolium Michx.');
insert into exercise (name, description) values ('Kreiger, Legros and Sipes', 'Hesperolinon adenophyllum (A. Gray) Small');
insert into exercise (name, description) values ('Wunsch LLC', 'Myuroclada Besch.');
insert into exercise (name, description) values ('Mitchell LLC', 'Arnica chamissonis Less. ssp. chamissonis');
insert into exercise (name, description) values ('McCullough, Leffler and Cummerata', 'Picramnia Sw.');
insert into exercise (name, description) values ('Walter and Sons', 'Camissonia cheiranthifolia (Hornem. ex Spreng.) Raimann ssp. cheiranthifolia');
insert into exercise (name, description) values ('Pfannerstill LLC', 'Tortella (Lindb.) Limpr.');
insert into exercise (name, description) values ('Ward LLC', 'Oclemena Greene');
insert into exercise (name, description) values ('Greenholt-Thompson', 'Solanum lanceolatum Cav.');
insert into exercise (name, description) values ('Turner Group', 'Anredera vesicaria (Lam.) C.F. Gaertn.');
insert into exercise (name, description) values ('Prosacco, Cruickshank and Graham', 'Dodecatheon conjugens Greene ssp. viscidum (Piper) H.J. Thomp.');
insert into exercise (name, description) values ('Daniel LLC', 'Manilkara jaimiqui (C. Wright) Dubard');
insert into exercise (name, description) values ('Hintz, Quitzon and Hintz', 'Stylisma Raf.');
insert into exercise (name, description) values ('Purdy-Bashirian', 'Tanacetum L.');
insert into exercise (name, description) values ('Mohr-Padberg', 'Bletia patula Graham');
insert into exercise (name, description) values ('Hansen LLC', 'Astragalus shevockii Barneby');
insert into exercise (name, description) values ('Goodwin LLC', 'Delphinium carolinianum Walter ssp. vimineum (D. Don) Warnock');
insert into exercise (name, description) values ('Cormier, Wolff and Wolf', 'Rubus trux Ashe');
insert into exercise (name, description) values ('Gislason-Gaylord', 'Ulota obtusiuscula Müll. Hal. & Kindb.');
insert into exercise (name, description) values ('Jaskolski-Daniel', 'Carex magellanica Lam. ssp. irrigua (Wahlenb.) Hultén');
insert into exercise (name, description) values ('Upton-Cartwright', 'Rhynchospora tracyi Britton');
insert into exercise (name, description) values ('Goldner-Donnelly', 'Opuntia basilaris Engelm. & J.M. Bigelow var. brachyclada (Griffiths) Munz');
insert into exercise (name, description) values ('Goyette Inc', 'Trillium chloropetalum (Torr.) Howell var. chloropetalum');
insert into exercise (name, description) values ('Bins-Spinka', 'Viola kauaensis A. Gray var. hosakae (H. St. John ) Havran & Ching Harbin');
insert into exercise (name, description) values ('Spinka-Runte', 'Hymenocallis choctawensis Traub');
insert into exercise (name, description) values ('Labadie, Johnston and Cronin', 'Lupinus brevior (Jeps.) Christian & D. Dunn');
insert into exercise (name, description) values ('Paucek LLC', 'Verrucaria ceuthocarpa Wahlenb.');
insert into exercise (name, description) values ('Yost, Cassin and Jast', 'Osmunda regalis L. var. spectabilis (Willd.) A. Gray');
insert into exercise (name, description) values ('Hand-Haag', 'Dryobalanops aromatica C.F. Gaertn.');
insert into exercise (name, description) values ('Bogisich and Sons', 'Phacelia suaveolens Greene');
insert into exercise (name, description) values ('Herzog, Okuneva and Lemke', 'Plantago eriopoda Torr.');
insert into exercise (name, description) values ('Ryan, Brown and Morar', 'Syzygium jambos (L.) Alston');
insert into exercise (name, description) values ('Thiel, Kuhn and Fritsch', 'Spergularia rubra (L.) J. Presl & C. Presl');
insert into exercise (name, description) values ('Flatley, Hauck and Krajcik', 'Caulanthus hallii Payson');
insert into exercise (name, description) values ('Bailey-Abernathy', 'Luzula divaricata S. Watson');
insert into exercise (name, description) values ('Kunze, Moore and Homenick', 'Urospermum Scop.');
insert into exercise (name, description) values ('Blick, Pfeffer and Barrows', 'Lobelia puberula Michx. var. simulans Fernald');
insert into exercise (name, description) values ('Hegmann-Gutmann', 'Corallorhiza maculata (Raf.) Raf. var. maculata');
insert into exercise (name, description) values ('Schiller-Osinski', 'Buellia silicicola de Lesd.');
